### PR TITLE
add minimum generation for Canary Islands

### PR DESCRIPTION
**Pull request by jarek**
Hi,

This should help #1330. Reported total generation below the following values will be rejected:

* ES-CN-FVLZ: 50 MW,
* ES-CN-GC: 150 MW,
* ES-CN-IG: 3 MW,
* ES-CN-LP: 10 MW,
* ES-CN-TE: 150 MW,
* ES-CN-HI: 2 MW

@strassburger can you take a look at these values and see if they are reasonable? They are intended to be a little lower than the lowest value we would expect to normally see.

### CODE REVIEW

**Comment by corradio** [comment]
Tests are failing:

```
======================================================================
ERROR: test_fetch_production (test_ES_CN.TestESIB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/circleci/electricitymap/parsers/test/test_ES_CN.py", line 113, in test_fetch_production
    self.assertEqual(production['zoneKey'], 'ES-CN-FVLZ')
TypeError: 'NoneType' object is not subscriptable
```

**Comment by systemcatch** [comment]
I think some of the mock datapoints (https://github.com/tmrowco/electricitymap/blob/master/parsers/test/test_ES_CN.py#L101) fail the new validate step and that results in None being appended to the list, which causes the assert to fail.

**Comment by jarek** [comment]
Ah thanks! Let's see if that fixes it

**Comment by jarek** [comment]
Actually this will still fail because test mocks 25 MW on FV/LZ and it expects to get it back from the parser. The parser won't return it now because that is way too low. The test is wrong IMO, I will update it later.

**Comment by corradio** [comment]
@jarek feel free to merge when ready.

**Pull request merged**
