### PR TITLE
Added PL translation

### PR DESCRIPTION
**Pull request by Pantkowsky**
Translated the EM website into polish. I had increased the width of left panel by 1rm to maintain the clear UI, as the translated words are quite long. The decision should be made regarding the 3rd screenshot (tooltip when hovering over the energy bar): should we manipulate the placeholders (as discussed on slack) to allow for proper semantics (the nouns in polish have different endings based on context), or should we increase the width of left panel by another 3-4rm, or should it be left as is (which is 90% correct grammatically).

untitled1

untitled

untitled2

### CODE REVIEW

**Comment by corradio** [comment]
This looks good to me. I'll make a tweet about having some PL speaking professionals validate the translation!

**Comment by Pantkowsky** [comment]
Basically the problem comes with the polish grammar. Polish has different endings, based on the context, for example the sentence in english:

Wind (energy) produces 17% of electricity in France
17% of French electricity comes from wind (energy)

Here, you have two different sentences, having the same meaning. In polish however, wind will be spelled differently for both sentences:

ENERGIA WIATROWA produkuje 17% energii elektrycznej we Francji
17% francuskiej energii elektrycznej pochodzi z ENERGII WIATROWEJ

For that reason, the tooltip translation gets kind of tricky, because there is wind (energia wiatrowa) and solar (energia słoneczna) but also Oil (ropa naftowa) or Coal (węgiel). So if the keyword *electricityfrom* has the translation of *pochodzi z* (comes from), then some of the sources (wind, solar, hydro, geothermal, nuclear) will not be spelled correctly, however if I add *energii* (energy) to it, then the situation is opposite - wind, solar, hydro, geothermal and nuclear are spelled correctly (as they are translated in polish into wind energy, solar energy etc, leaving it as wind or solar will not make any sense, cause it would be understood as wind and sun) but coal, oil and other will be translated wrong (coal energy, oil energy etc). This is why I was asking about manipulating the placeholders to an extent where the controller would understand which keyvalues to use for particular placeholders based on the context.

Everything else SHOULD be translated correctly, however double-checking with industry professionals would most definitely be profitable.

**Comment by corradio** [comment]
Any news here? Anyone we can ask for advice?

**Comment by Pantkowsky** [comment]
I don't unfortunately know anyone from the industry who could double check this PR ...

**Comment by corradio** [comment]
Hi @Pantkowsky,

I'd like to merge this one, even if we didn't double check it. People will submit fixes if they see bad translations :) 
The commit history is horrible however, and there's conflicts. Can you try to re-sync your fork in order to fix the conflicts?

**Comment by Pantkowsky** [comment]
@corradio sure, I should be able to fix it today in the evening. The conflicts are there because of (I suppose) updates added after that PR was made. Same goes for the commit history - initially there were between 5-10 commits from my branch as I remember, I don't know why suddenly it shows 300 of them. But as you see, the last commits in the entire list are the original ones regarding this PR :)

**Comment by corradio** [comment]
@Pantkowsky ??

**Comment by corradio** [comment]
Added manually. Closing

**Pull request closed without merging**
