### PR TITLE
Show US state lines within RTO areas

### PR DESCRIPTION
**Pull request by systemcatch**
As pointed out it's a little difficult to tell which states are within each RTO. Since state boundaries are very important to the way the country functions it's worth showing them in the merged areas. This will not effect the zone configurations.

ref #1046 

states

### CODE REVIEW

**Comment by jarek** [comment]
This is cool. To quickly confirm - does the hover highlight still work as currently? I'm also curious how it'll work when we have boundaries that don't follow state borders.

**Comment by systemcatch** [comment]
Hey jarek I made a gif showing the hover highlight on each area. I think the partial highlighting on MISO is related to #1058 and not to this change. For the future I don't think this method would work as there'd be overlap with some of the shape edges. Though maybe we could take a state boundary shapefile and merge it with our custom shapes so it's built in by default......

hover

**Comment by corradio** [comment]
Wow I'm impressed it actually works.
How come? Is it because geometries are added in a specific order and the aggregated ones end up showing on top? Or maybe you forgot to commit some files?

**Comment by systemcatch** [comment]
I think that's what's happening here, when the merged area is formed first then the underlying states won't show. Maybe this is due to how the internals of topojson.merge work (https://github.com/topojson/topojson-client/blob/master/README.md#merge). Looking at that page mergeArcs might help with performance?

The first time I saw this was when we were trying to split Chile into regions and I missed one state out when aggregating. Unintended but interesting feature.

**Comment by corradio** [comment]
I'm spending some time rewriting the geoJSON generation script to improve performance and clean it up.
I'm my next PR we will be able to tell which merges we want as a union (keeping inner arcs) and which we want to prune (removing inner arcs).
I'm therefore closing this, but stay tuned!

**Comment by systemcatch** [comment]
Sounds good let me know if you need a hand with anything.

**Pull request closed without merging**
