### PR TITLE
Separate Brazil into its grid subsystems

### PR DESCRIPTION
**Pull request by leorjorge**
The actual parsers still have to be done. This is the setup of the map, I was hoping to get feedback on that before looking for changing the parsers.

### CODE REVIEW

**Comment by leorjorge** [comment]
These are grid subsystems. Iirc they were isolated until some years ago. They also correspond more or less to geo-political divisions named formally regions (a couple states are in the "wrong" region, and two of them are clumped in the big central one here).

**Comment by corradio** [comment]
ok I was just wondering about how to name them.
Did you double check that each grid subsystem is strictly speaking an
aggregation of states (and not an approximation?)

On Thu, Sep 14, 2017 at 3:12 PM, Leonardo R. Jorge <notifications@github.com

**Comment by leorjorge** [comment]
As far as I could research, they correspond to the states. There are some isolated places not integrated into the system, but regardless, the integrated sites in each state are fed by the corresponding subsystems. 

With regard to names, the more appropriate would be North Brazil (BR-N), Northeast Brazil (BR-NE), Southern Brazil (BR-S) and, for the bigger one, there are some possibilities, as it lumps the Mid-west and southeastern regions. I guess the most intuitive would be Central Brazil (BR-CS).

**Comment by corradio** [comment]
Sounds good! Let's wait for the parsers to be ready and then I'll merge.

On Thu, Sep 14, 2017 at 4:03 PM, Leonardo R. Jorge <notifications@github.com

**Pull request merged**
