### PR TITLE
Split Brazil into regions

### PR DESCRIPTION
**Pull request by systemcatch**
I've modified the fetch_production function to accept the 4 regions (BR_CS, BR_N, BR_NE, BR_S) as arguments.  I've also split capacities by region using the ONS site.  The next step is either to create a new function for regional exchanges or modify the existing exchange function.

### CODE REVIEW

**Comment by corradio** [comment]
That's pretty cool! I'll merge everything at once. Do you think you can take a grab at the exchanges? Then we're all set

**Comment by systemcatch** [comment]
Sure I can create the exchange function.  Can you or @leorjorge / @alexanmtz setup the arrows?

**Comment by corradio** [comment]
I'll make sure to do it if they can't.

**Comment by alexanmtz** [comment]
I can setup the arrows

**Pull request merged**
