### PR TITLE
Revert day format of IN_PB

### PR DESCRIPTION
**Pull request by blackleg**
In that [commit](https://github.com/tmrowco/electricitymap/commit/43b135bde8a164c3d090d964c4c99e37e4f1f00f), the day format of the Punjab (India) consumption parser was changed to ```DD/MM/YYYY``` but the correct format is ```MM/DD/YYYY```.

It is very rare and it took time to realize when I made the parser.

### CODE REVIEW

**Comment by corradio** [comment]
Hi @blackleg,
I ended up changing the date format because the parser was bugging.
What is the rationale for changing back? I'm afraid we will have the same issue again?

**Comment by blackleg** [comment]
The date at the [website](http://www.punjabsldc.org/nrrealw.asp?pg=nrGenReal) from we obtain the consumption of Punjab state is shown in [month-day-year](https://en.wikipedia.org/wiki/Date_and_time_notation_in_India) format, for example, today 09/10/2017 the website show 10/09/2017. 

Can you give me more information about the bug it produces?

**Comment by corradio** [comment]
Mmh from what I remember the error was that I couldn't parse a date because the format was invalid. I suggest, in order to be 100% sure, to wait for the 13th of October, where we will know for sure if the current implement is correct, or if I made a mistake doing the change.
How does that sound?

**Comment by blackleg** [comment]
It's ok for me.

**Pull request merged**
