### PR TITLE
Create Malaysian exchanges with Thailand & Singapore

### PR DESCRIPTION
**Pull request by systemcatch**
Scraping aspx pages is no fun. These functions can return 10min data for the current day. The Singapore arrow dwarfs the country!

/cc @maxbellec might be some inspirations for UY past dates here.

ref #809 

my_exchanges

### CODE REVIEW

**Comment by jarek** [comment]
From first look code looks nice, I'll take a deeper look later.

That exchange arrow really does look a bit silly. How would it look moved a bit further north so that Singapore is more easily clickable? Though that might cause weirdness at different zoom levels.

**Comment by alixunderplatz** [comment]
From what I can evaluate, everything is assigned to the proper zone.

I'd also move that exchange arrow to be completely inside the tip of Malaysia, so Singapore is still accessible. I think it will be quite helpful to enhance that tiny Singapore also has data.

**Comment by systemcatch** [comment]
Ok I will move the arrow north into Malaysia and rotate counter clockwise slightly so Singapore is more visible.

**Comment by jarek** [comment]
Code looks really good! You've managed to make the painful ASP.NET postbacks look logical!

It is currently 29.03. 01:52 in Malaysia, https://www.gso.org.my/SystemData/TieLine.aspx does not yet have any data for 29th (in fact it looks like exchanges have not updated since 28.03. 20:10?). If you care to catch the exception:

```
Traceback (most recent call last):
  File "MY_WM.py", line 345, in <module>
    print(fetch_exchange('MY-WM', 'TH'))
  File "MY_WM.py", line 312, in fetch_exchange
    processed_egat = xml_processor(egat_data)
  File "MY_WM.py", line 195, in xml_processor
    raw_data = ElementTree.fromstring(text)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1325, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 19, column 13
```

The offending line 19 seems to be: `<table width=100%><tr><td></td><td align=right><table><tr><td><span id="toolbar_User"></span></td><td><span id="toolbar_Station"></span></td><td><span id="toolbar_Date"></span></td></tr></table></td></tr></table></rl>`

I've no idea what the `</rl>` is supposed to be... Maybe xml lib of newer Pythons can deal with this better.

And at 01:58, I got a yet different error:

```
Traceback (most recent call last):
  File "MY_WM.py", line 346, in <module>
    print(fetch_exchange('MY-WM', 'TH'))
  File "MY_WM.py", line 305, in fetch_exchange
    egat_hidden_values = extract_hidden_values(req)
  File "MY_WM.py", line 176, in extract_hidden_values
    viewstategenerator = soup.find("input", attrs={'id': '__VIEWSTATEGENERATOR'})['value']
TypeError: 'NoneType' object is not subscriptable
```

These aren't really parser errors, of course, they're underlying data errors...

**Comment by systemcatch** [comment]
Moved the arrow so that Singapore is visible again.

mysgarrow

**Comment by systemcatch** [comment]
@jarek thanks I had to sacrifice (or post?) several small furry animals to the ASP.NET gods to get this to work but overall I understand these pages much better now.

It looks like https://www.gso.org.my/SystemData/TieLine.aspx has updated with data for 29th now. I think when there's no data available html is returned rather than xml which results in the failure.

The 2nd error is very weird as I thought the viewstategenerator tag always loads with the page. Only explanation is that the page failed to load properly.

**Comment by systemcatch** [comment]
I'll merge this later on today unless there's any other points raised.

**Comment by maxbellec** [comment]
that's awesome @systemcatch. Super clean code for a super ugly task :1st_place_medal:

**Pull request merged**
