### PR TITLE
Add flake8 tests to circle.yml

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by corradio** [comment]
Thanks for the pull request @cclauss. Is this still relevant given https://github.com/tmrowco/electricitymap/pull/949#issuecomment-354424917?

**Comment by cclauss** [comment]
Still relevant.  Please put these tests in place to aid our transition to Python 3.

**Comment by corradio** [comment]
I'm closing this as it seems to be part of https://github.com/tmrowco/electricitymap/pull/949.

**Comment by cclauss** [comment]
We want to see it running on Python 2 before we switch to Python 3.

**Pull request closed without merging**
