### PR TITLE
Albania hardcoded export emission factor

### PR DESCRIPTION
**Pull request by alixunderplatz**
Default source for generation in 2015:
https://www.iea.org/statistics/statisticssearch/report/?country=ALBANIA&product=electricityandheat&year=2015

New hydro power is supposed to come online this year. Currently up to 1800 MW generation based on the links I gave in #1062

Bit longer article on the current and future capacity development, if you're interested:
https://www.energyworldmag.com/electricity-generation-capacity-development-albania/
It says there is a CCGT gas power plant, but according to other [news](https://seenews.com/news/albania-plans-to-feed-gas-from-tap-pipeline-into-idled-vlora-tpp-532173), it was never put into operation since 2011 due to mechanical faults. 

Also there is some generation from waste but with max of 2.85 MW, so insignificant atm. 
PV capacity will slowly rise, tenders are expected. If any new capacity is added, it will still be represented by the "100% renewable" ratio.
Potential is between 1500 to 1800 kWh/kWp, so 100 MWp PV will translate into 150 to 180 GWh/a in the future.

### CODE REVIEW

**Comment by jarek** [comment]
Does Albania often/ever import and export at the same time?

**Comment by alixunderplatz** [comment]
@jarek very good point!
I guess your concern is also going in the direction that the intensity is wrong/worse if there is at least one import from the other zones.

Looks like Albania was heavily importing from Greece and Montenegro **in 2017**.
Here is the percentage of hours for the directions of flow to each neighbour (source ENTSO-E physical cross border flow):

image

Looking at the simultaneous occurrence of either imports or exports:
66 hours with export to all directions at the same time, 4175 hours of import from all directions at the same time.

This year, **so far** the situation looks totally different.

image

There already were 1196 hours (of 1968 analyzed) of simultaneous export in all directions, because probably there were some new hydro power plants that were put into operation and there is enough available water, too. No simultaneous imports from all sides. Exports to Serbia 100% of time so far.

**Comment by jarek** [comment]
Hmm. Yeah we'd try to avoid situations where Albania transfers large amounts of electricity without generating much, but magically making it cleaner through the exchange hardcode.

Can you easily have an overview of the ratio of local production vs imports in 2018 in situations when they were both importing and exporting?

**Comment by alixunderplatz** [comment]
@jarek 
Visualization of the imports and exports as time series for 2018:
Only some imports at all at the beginning of the year from ME, but still less than what was exported in the balance (red line, positive all the time):

image

What is a bit special is this: it seems like there is a constant amount of generation leaving to RS/Kosovo (yellow line), starting in February. First it is around 100 MW, then around 200 MW. It is possible that the grid is used to export the entire generation of one power plant or some units via a seperate power line.
Looking at the topology there is one 220 kV and one 380 kV line to RS/Kosovo, and the Fierze substation in AL has a HPP with 4x 125 MW connected to it.

From February, around half of the generation of AL (estimate by me, haven't yet calculated it) is exported and there barely were any imports.
So the intensity factor is valid at the moment.

**Comment by jarek** [comment]
The chart is convincing for me and I have no more questions :+1: - let's wait for @brunolajoie

**Comment by alixunderplatz** [comment]
@jarek @brunolajoie this situation may change as soon as the hydro generation decreases. (Generation diversity in the portfolio is a must for Albania.) 
I will track it and in case transit flows will be dominant, disabling the intensity for AL is the only option.

**Comment by brunolajoie** [comment]
We couldn't validate hardcoding this export intnesity factor without a continuous check of AL import/export balance like the one you suggested above @alixunderplatz. Trusting your commitment on this, I'll approve the PR. Feel free to merge if you want to follow up on that 💪

**Pull request merged**
