### PR TITLE
Use CO₂ instead of CO2

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by corradio** [comment]
Hello @magol, thanks for the pull!
Do you know if the follow is compatible with SEO? I'd be afraid that using the special "2" subscript character might prevent us from being index with "CO2".

**Comment by magol** [comment]
@corradio Hmm,  good question That is one aspect I have not thought of.

It may be better to use <sup> instead of unicode characters where possible. Then the search engines consider it a regular 2.

**Comment by corradio** [comment]
Sounds good!

**Comment by magol** [comment]
@corradio Now I have replaced the `&#8322;` with `<sub>2</sub>`

**Comment by magol** [comment]
An alternative is to use CSS to make the 2 smaller.  But I suggest to leta it be as it is, it is acceptable

**Comment by magol** [comment]
@corradio I did not expect that this to happen, so I did not test. :persevere: I should know better. 

I have now set up an test environment and update it to work as expected.
But I do still have a issue, I don't know how to handle. I'm a C++/C# programmer,  and I'm not so used to JavaScript.

`misc.maintitle` do have a `CO<sub>2</sub>` and is used in multiple places, eg. `<title>`and `<meta property="og:title"`. The consequences is that it become a `<sub>` in the `<title>`, and that is wrong. I have multiple ideas how to solve this, but as I don't know JavaScript that well and not know what you prefer I let you decide how to do.

Some ideas I have:
 - Create a secondary `misc.maintitle` that don't have any `<sub>`
 - Create a function that remove the <sub> that are used by `<title>` and `<meta property="og:title"`
 - Fix it in the compilation step (I don't know if it is possible)
 - Something entirely different

**Comment by corradio** [comment]
To be honest, I don't think we should have any html tags in the JSON. It's insecure and might lead to the mistakes you mention.
I had another idea: what about we write a JS function in `server.js` that replaces `CO2` with `<sub>CO2</sub>` that we can use in all markups where we want to style CO2 properly?
Like for example:

```html
<div>
  <%= co2sub(__('title.misc')) %>
</div>
```

**Comment by magol** [comment]
Good idea. I had the same thoughts as you, but I was not sure if that was a good idea.
I'll see if I'm able to fix it, good to learn new languages.

**Comment by magol** [comment]
But is not the performance affected by doing search and replace in all text string for each page load?

**Comment by corradio** [comment]
It's actually a very little find/replace because it's only done on the
specific translated string, and only when we explicitly wrap it in the "co2
detector" function.
It's almost no overhead.

**Comment by magol** [comment]
@corradio I have now added a function to make the formatering of CO2. 
But now I have one function in [index.ejs](https://github.com/magol/electricitymap/blob/c2c8581ae518f3de5d5b2c2f80f0953a287a7c3b/web/views/pages/index.ejs#L2) and one in [toolltip.js](https://github.com/magol/electricitymap/blob/c2c8581ae518f3de5d5b2c2f80f0953a287a7c3b/web/app/tooltip.js#L57) that do the same thing. I have never worked whit this before, is it any way to only have the code in one place?

**Comment by corradio** [comment]
That's ok for now as we need to harmonize and merge both language systems.
However, please make sure to use the same function name (right now one is with a lowercase "s" and the other with an uppercase "s").

**Comment by magol** [comment]
@corradio Thank you for you feedback. I will fix the naming and clean up the history so that it finely can be merged :-)

**Comment by magol** [comment]
@corradio I think it is ready for merge now :-)

**Comment by corradio** [comment]
Good job!

**Comment by corradio** [comment]
Good job!

**Pull request merged**
