### PR TITLE
Norwegian and Swedish bidding zone geometries (#1381)

### PR DESCRIPTION
**Pull request by tmslaine**
Upload of approximate bidding zone geometries for the Norwegian and Swedish bidding zones NO1-NO5 and SE1-SE4. Based on the zones shown on Nätområden.se(Sweden) and NVE map service layer "NVE Elspot områder"(Norway).
se_no_bzn

### CODE REVIEW

**Comment by corradio** [comment]
Awesome! This will be a great help for #1381.
@maxbellec can we start adding bounding boxes and weather data for those?

**Comment by corradio** [comment]
Awesome! This will be a great help for #1381.
@maxbellec can we start adding bounding boxes and weather data for those?

**Comment by maxbellec** [comment]
@tmslaine do you know if the bidding zones have proper names that we could show on the map? Or should we just call them NO1 - NO5?

**Comment by tmslaine** [comment]
https://www.nordpoolspot.com/globalassets/download-center/day-ahead/elspot-area-change-log.pdf has city references and the following descriptive names for NO1-NO5:
NO1: Southeast Norway
NO2: Southwest Norway
NO3: Middle Norway
NO4: North Norway
NO5: West Norway

For the Swedish bidding zones something like:
SE1: Northern Norrland
SE2: Southern Norrland
SE3: Central Sweden
SE4: South Sweden
will probably do.

**Pull request merged**
