### PR TITLE
Split Canary Islands parser.

### LINKED ISSUE #626: Split generation by island for Canaries
Is it possible to split canary island into the islands.
they are really working for there own.
see  also:
http://ree.es/en/activities/canary-islands-electricity-system/canary-electricity-demand-in-real-time

El Hierro is very impressiv: rigth now 100% RE /  0 CO2
source:
https://demanda.ree.es/movil/canarias/el_hierro/total

### PR DESCRIPTION
**Pull request by blackleg**
Split the Canary Islands parser to get data from each island and use [the new shapefiles](https://github.com/tmrowco/electricitymap/pull/1022).

Fixes #626

### CODE REVIEW

**Comment by corradio** [comment]
Looks good. Can you use the mockserver and post a screenshot so we are sure the parsers work?

**Comment by strassburger** [comment]
corradio:
"Can you use the mockserver and post a screenshot so we are sure the parsers work?"
Sorry, not able to use the mockserver now.
started with:
Running locally:
To get started, clone or fork the repository, and install Docker.
worked fine:
https://help.github.com/articles/cloning-a-repository/
Failed here with docker, only have 32bit ubuntu machines till now, sorry.
So can not help here, need more help......
Sure that El hierro Will be in 1.place rigth now in ranking in the test run.
Working temporaly 100% wind.

**Comment by corradio** [comment]
OK I'll checkout your branch and test myself then. Will do that asap!

**Comment by blackleg** [comment]
screen shot 2018-01-27 at 17 48 04

**Comment by blackleg** [comment]
I forgot upload the screenshot yesterday.

**Comment by corradio** [comment]
Looks nice! No interconnectors at all?

**Comment by strassburger** [comment]
Only Fuerteventura + Lanzarote have a interconnector.
all other islands solo: very deep ocean is the reason.

**Comment by blackleg** [comment]
@corradio I assumed that Lanzarote and Fuerteventura is one system because the endpoint that use to extract data contains the aggregate data of [both islands](https://demanda.ree.es/movil/canarias/lz_fv/total).

**Comment by corradio** [comment]
Makes sense.

**Pull request merged**
