### PR TITLE
Feature/hide offscreen arrows

### PR DESCRIPTION
**Pull request by scarlac**
This should help performance when viewing other regions. We'll eventually have so many animations that we'll need to hide those not relevant. Ideally this would be handled by the browser, but we're translating which means browsers are may not be detecting the offscreen content.

### CODE REVIEW

**Comment by scarlac** [comment]
Okay, not ready to be merged yet. Seems zoom factor is messing up the calculations. Will return with a fix.

**Comment by corradio** [comment]
OK noted. Thanks for helping on this. Let me know when you want me to review.

**Comment by scarlac** [comment]
I've included scale factor in the calculations. I've been unable to verify any performance implications myself, so if we have a setup that struggles with CPU usage in other regions, let me know so we can test this branch. Otherwise, it may not be worth to include to code.

**Comment by corradio** [comment]
I'll try it out on my iPhone 5S to see if it helps.

Olivier

**Comment by corradio** [comment]
Things to check:
- [ ] Re-rendering the arrows on drag end does not induce significant delay.

I'll do the checklist.

**Pull request merged**
