### PR TITLE
Ru parser

### PR DESCRIPTION
**Pull request by denplis**

### CODE REVIEW

**Comment by denplis** [comment]
@corradio 
Yes. This parser is for whole Russia Region. But it could be separated at least by two regions.
Only the wind/solar production is missed, and all fossil production is summarized.
I try to separate fossils by average production share.

Also, there exist production power by small regions  http://br.so-ups.ru/Public/MainPageData/VSVGO/PowerVIEByRegions.aspx
But the data from this url is ahead for a few days. Don't know is it forecast or real production with the broken date. I'll check later.

**Comment by denplis** [comment]
@corradio 

> Re. fossil breakdown, I actually don't like estimating the breakdown. Let's try to stick as close as possible to the data source. You can simply set all fossil to the "unknown" key (it's considered fossil in our CO2 models).

Average `unknown` type is 700 gCO2eq/kWh.
Breakdown fossil by approx production type take to us 585.7 gCO2eq/kWh. for all fossils.
0.71 * 490(gas) + 0.29 * 820(coal) = 585.7 gCO2eq/kWh.
700 and 585.7 is a huge difference.

I know, 585.7 isn't accurate. But equating all fossils to unknown (  700 gCO2eq/kWh ) if we know that gas is almost 3/4 of fossils production is less accurate from my vision. What do you think?

**Comment by corradio** [comment]
I understand you point, but however I value higher data consistency.
What we could do is still keep fossil production data as unknown, but use 585.7 as "unknown" emission factors instead of 700 for RU.
This can be changed here:
https://github.com/tmrowco/electricitymap/blob/master/config/co2eq_parameters.js

Another issue is that because this data source returns estimated data, I'm not sure whether or not to include it. Let's discuss this in the associated issue #757

**Comment by alixunderplatz** [comment]
@corradio I think we're ready to get Russia going as a whole. Please see my latest comment in #757 
unknown emission factor is 567 g/kWh (really close to @denplis estimate)

**Comment by corradio** [comment]
In this PR we still need to
- remove fossil fuel breakdown estimations
- make sure default values are None instead of 0 (to distinguish between a value that is unknown and a value that is known to be 0)

**Comment by systemcatch** [comment]
We will also need to make sure the parser runs in Python 3.

**Comment by alixunderplatz** [comment]
@systemcatch everything that is now assigned to "fossil types" in the current parser code ("thermal" power stations (TES or ТЭЦ), "condensation type" power stations (GRES or ГРЭС) and "combined heat-and-power" stations (BS or БС) belongs to the unknown part.

**Comment by corradio** [comment]
Thanks for starting this @denplis.
I'm closing because we merged #1066

**Pull request closed without merging**
