### PR TITLE
Update german capacity

### PR DESCRIPTION
**Pull request by Maverick78de**
Updated german power plants 
https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/kraftwerksliste-node.html

### CODE REVIEW

**Comment by jarek** [comment]
Hello,

Thank you for the update. As I understand it, the data is from https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/Kraftwerksliste_2017_2.xlsx?__blob=publicationFile&v=2 linked on https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/kraftwerksliste-node.html tab "Auswertung Energieträger".

Can you confirm how the exact categories are grouped in biomass and gas? E.g. the source gives "Biomasse" capacity as 7354 MW while you have 7546 MW. Trying to add in e.g. Deponiegas I couldn't get to exactly 7546 MW.

Further, can you update the main README file to point to the link given in the "Production capacity data sources" section? We currently specify https://energy-charts.de/power_inst.htm as source. Do you think Bundesnetzagentur is a better source?

**Comment by Maverick78de** [comment]
Hello, 
"Bundesnetzagentur" should be the primary source because all power sources need to be registered and there by law.
At "biomass" I added "Klärgas", I found no clear definition which kind of power source can be added to biomass. On some sites a lot of sources will be added to biomass e.g. garbage.

**Comment by jarek** [comment]
@corradio @brunolajoie can you confirm how the different sources in the xlsx linked above should be categorized?

**Comment by brunolajoie** [comment]
Hello!

In our "biomass" category, we gather anything related to organic compound: woody biomass, biogas (so Klärgas is part of it yes), waste, peat, landfill, etc...

Data seems good to me at first sight, will approve after readme has been updated.

Thanks a lot guys!

**Comment by alixunderplatz** [comment]
@brunolajoie 
Just wanted to add that half of the electricity generated from waste combustion in Germany is considered to come from organic/biological waste components, the other half comes from waste components with fossil origin like plastic, waste oil, solvents etc.

See annotation "4" below the table of this annual paper ([Link to image source](https://www.umweltbundesamt.de/sites/default/files/medien/376/publikationen/erneuerbare_energien_in_deutschland_daten_zur_entwicklung_im_jahr_2016.pdf)):
image

As far as I remember, these 50% are based on some research work related to the average waste composition.
But it's no big deal since only ~6 TWh (< 1% of total generation) were produced from waste in the past.

**Comment by brunolajoie** [comment]
Thanks a lot for the insight @alixunderplatz. Let's keep that in mind for when we will refine GHG-emission factors of German power plants. 

As this PR only concerns installed capacities, I'm gonna merge it anyway, because capacities won't impact GHG-computation on the ElectricityMap.

**Pull request merged**
