### PR TITLE
Split Chile into grid regions

### PR DESCRIPTION
**Pull request by systemcatch**
I've created a new function that allows us to define the CL-SIC grid region and used existing functions to define the 3 other regions.

#840

### CODE REVIEW

**Comment by corradio** [comment]
Code looks good. Can you post a screenshot before I merge (just want to make sure it works).

**Comment by corradio** [comment]
@systemcatch almost seems to work:

image

There's a small piece at the border with Peru that disappeared :(

**Comment by systemcatch** [comment]
That small region at the top is the [Arica_y_Parinacota](https://en.wikipedia.org/wiki/Arica_y_Parinacota_Region) region.  Though it is a relatively new [addition](https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/iso_3166-2_newsletter_ii-2_2010-06-30.pdf) to ISO 3166-2 the code_hasc tag is in the data.  The only things that are different in that region compared to the other 2 regions that form SING are that it doesn't have postal or fips data, but neither of those things should matter based on how we are getting the the states.

Racking my brain for an explanation, @jarek any ideas?

**Comment by jarek** [comment]
I can take a look on Thursday @systemcatch

**Comment by corradio** [comment]
I'm having a look now to see if I can bring in some help.

**Comment by corradio** [comment]
I've actually been able to find that region in the states file:
```bash
web❯ cat world_states_props.json |grep Arica|jq '.'
{
  "adm1_code": "CHL-2694",
  "OBJECTID_1": 2740,
  "diss_me": 2694,
  "adm1_cod_1": "CHL-2694",
  "iso_3166_2": "CL-",
  "wikipedia": null,
  "iso_a2": "CL",
  "adm0_sr": 1,
  "name": "Arica y Parinacota",
  "name_alt": null,
  "name_local": null,
  "type": "RegiÃ³n",
  "type_en": "Region",
  "code_local": null,
  "code_hasc": "CL.",
  "note": null,
  "hasc_maybe": null,
  "region": null,
  "region_cod": null,
  "provnum_ne": 0,
  "gadm_level": 1,
  "check_me": 20,
  "scalerank": 3,
  "datarank": 3,
  "abbrev": null,
  "postal": null,
  "area_sqkm": 0,
  "sameascity": 7,
  "labelrank": 7,
  "featurecla": "Admin-1 scale rank",
  "name_len": 18,
  "mapcolor9": 5,
  "mapcolor13": 9,
  "fips": null,
  "fips_alt": null,
  "woe_id": 56043702,
  "woe_label": "Arica and Parinacota Region, CL, Chile",
  "woe_name": "Arica y Parinacota",
  "latitude": -18.3207,
  "longitude": -69.6804,
  "sov_a3": "CHL",
  "adm0_a3": "CHL",
  "adm0_label": 2,
  "admin": "Chile",
  "geonunit": "Chile",
  "gu_a3": "CHL",
  "gn_id": 6693562,
  "gn_name": "Region de Arica y Parinacota",
  "gns_id": 10749159,
  "gns_name": "Arica y Parinacota, Region de",
  "gn_level": 1,
  "gn_region": null,
  "gn_a1_code": "CL.16",
  "region_sub": null,
  "sub_code": null,
  "gns_level": 1,
  "gns_lang": "ara",
  "gns_adm1": "CI16",
  "gns_region": null
}
```

**Comment by corradio** [comment]
Just for the sake of being sure of completeness, I've outputted the list of adm0:
```bash
cat world_states_props.json |grep Chile|jq '.adm1_code'
"CHL-2691"
"CHL-2692"
"CHL-2693"
"CHL-2694"
"CHL-2695"
"CHL-2696"
"CHL-2697"
"CHL-2698"
"CHL-2699"
"CHL-2700"
"CHL-2701"
"CHL-2702"
"CHL-2703"
"CHL-2704"
"CHL-2705"
```

and list of `code_hasc`:

```bash
cat world_states_props.json |grep Chile|jq '.code_hasc'
"CL.AI"
"CL.MA"
"CL.TA"
"CL."
"CL.AN"
"CL.AT"
"CL.CO"
"CL.RM"
"CL.VS"
"CL.AR"
"CL.AR"
"CL.BI"
"CL.LI"
"CL.LL"
"CL.ML"
```

**Comment by systemcatch** [comment]
@corradio nice work!  When did you last get the natural earth states file from their server?  They did an [update](https://github.com/nvkelso/natural-earth-vector/blob/master/CHANGELOG) in October and apparently CL. was changed to CL.AP!  Hence why it wasn't mapping on your build.

I can either change the code_hasc to CL. or if you want to use the latest file then everything should work as is.

**Comment by corradio** [comment]
I did an update right now (by running topogen.sh).
I can send you the world.json file on Slack, then you can do all the tests
you need!

**Pull request merged**
