### PR TITLE
Panama parser

### PR DESCRIPTION
**Pull request by 7hibault**
See #696

### CODE REVIEW

**Comment by corradio** [comment]
Looks good! Can you try running it using the mockserver and post a screenshot to double check all is working? (see README)

**Comment by 7hibault** [comment]
I'm having trouble running the mockserver: 

> Oops! We are having trouble reaching the server. We will try again in a few seconds. Retry now.

Running the test command seems alright but won't change anything to the map (even after refresh)

```
$ PYTHONPATH=. python mockserver/update_state.py PA
Finding and executing PA production parser PA.fetch_production..
{ 'countryCode': 'PA',
  'datetime': datetime.datetime(2017, 12, 13, 10, 26, 22, tzinfo=tzfile('/usr/share/zoneinfo/America/Panama')),
  'production': { 'gas': 2.29,
                  'hydro': 1044.24,
                  'solar': 58.11,
                  'unknown': 60.69,
                  'wind': 178.9},
  'source': 'http://sitr.cnd.com.pa/m/pub/gen.html',
  'storage': { }}
Finding and executing CR->PA exchange parser ENTE.fetch_exchange..
{ 'datetime': datetime.datetime(2017, 12, 13, 9, 26, tzinfo=tzstr('UTC-6')),
  'netFlow': -47.399999999999999,
  'sortedCountryCodes': u'CR->PA',
  'source': 'enteoperador.org'}
Updating and writing state..
..done
```

**Comment by systemcatch** [comment]
Looks good, the only things I would say are should their 'biogas' be mapped to the 'gas' label?  Also the source link can be reduced to cnd.com.pa

**Comment by 7hibault** [comment]
@systemcatch Yes, I ran `docker-compose run --rm web npm run watch` in a terminal, then leave it hanging and run `docker-compose up --build` in another and this is what I get before and after running `PYTHONPATH=. python mockserver/update_state.py PA`. 

screenshot_20171213_170330

I must be missing something dumb somewhere :)

**Comment by corradio** [comment]
Fixed. You just need to resync your fork and run `docker-compose build`.

**Comment by 7hibault** [comment]
Ok now I can build and run it again. This seems alright, what do you think?

screenshot_20171214_125533
screenshot_20171214_125448

**Comment by corradio** [comment]
Hurray! Sounds good

**Pull request merged**
