### PR TITLE
Fixed typo in german locale

### PR DESCRIPTION
**Pull request by jld3103**

### CODE REVIEW

**Comment by alixunderplatz** [comment]
Hey @jld3103, while you're at it, can you fix the whitespaces in *Nord Insel* and *Süd Insel* and make them *Nordinsel* and *Südinsel* and add a comma in "Wirke mit, indem du ...". 
Thanks :)

**Comment by jld3103** [comment]
Thanks @alixunderplatz. Did it.

**Comment by jarek** [comment]
@alixunderplatz @jld3103 This doesn't really block the merge here, but maybe something for you to look at: we mix usage of "Du"/"Dein" and "du"/"dein", presumably standardizing on one would be good. Also if you have the time, translating the onboarding screens (you can see them by visiting the site in private browsing mode/without cookies) would be awesome!

I'll merge this PR, thanks for the contribution @jld3103!

**Comment by jld3103** [comment]
@jarek look #1407

**Pull request merged**
