### PR TITLE
Costa Rica unknown plants

### PR DESCRIPTION
**Pull request by systemcatch**
This sets any plant that isn't in CR's plant mapping to 'unknown', preventing a KeyError occurring like in #760 .

### CODE REVIEW

**Comment by corradio** [comment]
Are you sure we should do that? If we have an error then we know we have to change the mapping, instead of silently classifying to unknown.

**Comment by systemcatch** [comment]
The AR/DO/NI parsers are currently setup like this.

My thought is it's better to do this rather than allowing a KeyError (I'm assuming you lose the datapoint if that happens?).  Trying to maintain the plant mappings for many parsers reactively seems difficult.  I guess though we want to map new plants quickly like you say rather than letting them silently go to 'unknown' for ages.

Maybe we could do something to list all unknown plants for each parser that uses plants,  e.g. logging/debug/create a function.  That way it would be easier to update the mappings and it would give people a good way to make a small contribution by classifying those plants.

**Comment by corradio** [comment]
In that case I suggest adding a print statement (that will be caught by the
logger) stating that the key is missing, but classifying as unknown.
That way we don't lose the datapoint, but I'll catch the message and make
sure we update it

**Comment by systemcatch** [comment]
Ok so all I need to do is setup a print statement listing unknown plants and the backend will deal with that properly?

**Comment by corradio** [comment]
Yes: if you encounter a missing key, simply print it and it will be added to the logs.

**Comment by systemcatch** [comment]
Right this should now print all plants that are not part of the mapping.  I think I made a mistake with git though (all the extra commits), let me know if that's a problem and I can resubmit the PR in a cleaner form.

**Pull request merged**
