### PR TITLE
Create Thailand generation mix and CO2 intensity

### PR DESCRIPTION
**Pull request by zarppy**

### CODE REVIEW

**Comment by zarppy** [comment]
Just update  the data of Thailand. Anyone wants to validate and make it go live?

**Comment by corradio** [comment]
Hi @zarppy ,
It seems like you have hardcoded data, and that no live data is used. Have you found a live data source?

**Comment by zarppy** [comment]
Hi,

Thanks for your email. Apologies since I haven't checked the requirement
that you need a live data source. However, there is no sort of thing
publicly available in Thailand anyway.

If that the case, you can simply ignore it if the set of data provided may
not really useful.

Cheers
Zarppy

*Win Chanvittayanuchit*
*PhD Student | Australian-German Climate and Energy College*
The University of Melbourne, Australia
M: +61 436 029 563
E: pchanvittaya@student.unimelb.edu.au

**Comment by corradio** [comment]
ok I will close this for now. Please let me know if you find a real-time data source for Thailand, this would be super helpful!

**Comment by TomHetmer** [comment]
How realtime does it have to be? Is there a standard for this? For example thailand has monthly data.
Either you can map anything best you can get or you’ll leave all developing countries gray until they discover APIs in 59 years.

**Comment by skovhus** [comment]
@TomHetmer you can read more about our _current_ requirements for the live data here: https://github.com/tmrowco/electricitymap-contrib/wiki/Technical-requirements-for-parser-data

But we are exploring options to show the best available data on the map as not all zones have live data available.

**Pull request closed without merging**
