### PR TITLE
Localize Database and Forecast

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by corradio** [comment]
Hi @magol,
Thanks for the PR. Unfortunately Live, Database, Pro and Forecast are brands so they shouldn't be translated. Can you revert those? Thanks.

**Comment by magol** [comment]
Ahh, I understand. 
But, "Pro" isn't anything new. It was localized by me already in November (PR #839). Should I revert that to?

**Comment by corradio** [comment]
Yes that'd be great if you could remove references to "pro". Thanks!

**Comment by magol** [comment]
@corradio Ok, I have removed the localizations of the strings now :-)

**Comment by magol** [comment]
@corradio In the commit history, it now say "Localize Database and Forecast". It's quite misleading, and I wonder if it's possible to change that commit message.

**Comment by corradio** [comment]
No worries at all. It's quite complicated to change previous commit messages.

**Pull request merged**
