### PR TITLE
update CR parser, allow fetching past data

### LINKED ISSUE #1266: Costa Rica
Costa Rica is showing as N/A on your map.  They are 99% renewable.  https://www.independent.co.uk/news/world/americas/costa-rica-electricity-renewable-energy-300-days-2017-record-wind-hydro-solar-water-a8069111.html

### PR DESCRIPTION
**Pull request by jarek**
- HTML of the source had changed a bit, fix #1266
- past production data back to 2007 can be fetched, re #1257 
- update logging messages a bit

I hope that's enough to justify my shameless self-promotion in zones.json

### CODE REVIEW

**Comment by systemcatch** [comment]
Nothing wrong with a bit of self promotion :wink: ! Do you want to build this branch and update the mockserver state to check everything is ok?

**Comment by jarek** [comment]
Ah, running front-end doesn't really work for me, my one machine has a super-broken Docker install and the other VM runs out of disk space... so I usually just test on commandline only

**Comment by systemcatch** [comment]
Is your machine running Windows?

I got your branch to build and run ok, so we should be good to go here.

jarek_cr

**Comment by jarek** [comment]
My one machine has a only-somewhat-updated Ubuntu 15.04 (that's the broken Docker), the other is a Windows I don't use much with too-small Linux VM... Sorting it all out is on the todo list :P 

I think I'll just merge it and see how it goes, it can't be any worse than not working at all.

**Comment by systemcatch** [comment]
Heh I finally made the jump from Ubuntu 14.04 to 16.04 after delaying for ages so I know all about the todo list!

**Pull request merged**
